# Generated by Django 5.1.7 on 2025-04-25 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('sigrc', models.IntegerField()),
                ('tipo', models.CharField(choices=[('ALERTA', 'Alerta'), ('EMERGENCIA', 'Emergência')], default='ALERTA', max_length=50)),
                ('motivo', models.CharField(max_length=255)),
                ('data', models.DateField()),
                ('endereco', models.CharField(max_length=255)),
                ('bairro', models.CharField(max_length=255)),
                ('distrito', models.CharField(max_length=255)),
                ('area_risco', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
